---
validator_registration_topic: 610eb3c1fafe229af536e91b7e00486902d54d54d8d3f0de283a467ac8f985bf
validator_removal_topic: 671ada3835502b9498e4a3116c344293ec3a4ef43f90bb42283d7d66a3f772b2
initiator_registration_topic: 3ed0a993c042af686c0f93773269df3a1874729d2b4fc3f71fdaa684bb2d6755
initiator_minipool_created_topic: d37d31a5a66d534ce3b071e3ee6cf8b7d36a6dd20aa4f08e9cec322b27bd7704
initiator_minipool_ready_topic: c474edb44e2d7e6c7f20261d61afed24712bcbd6a0799ae5b0786626c47da63c
initiator_removal_topic: 34ecedfa430a18df6cda4bc2313d74d224c6742df8e6a98eca2fda96b69a050d
safestake_network_abi_path: contract_config/SafeStakeNetwork.json
safestake_registry_abi_path: contract_config/SafeStakeRegistry.json
